name: Qodana
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions: write-all

#    permissions:
#      contents: write
#      pull-requests: write
#      checks: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Qodana Scan
        uses: JetBrains/qodana-action@latest
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_280741207 }}
          QODANA_ENDPOINT: https://qodana.cloud

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
          ref: "refs/heads/${{ github.head_ref }}"
          sha: ${{ github.sha }}
